"""empty message

Revision ID: e8fefaae8863
Revises: dc86fa553ae8
Create Date: 2022-04-11 11:02:15.375153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fefaae8863'
down_revision = 'dc86fa553ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aisle_1_unused', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'user', ['aisle_1'])
    op.create_unique_constraint(None, 'user', ['aisle_1_unused'])
    op.drop_column('user', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('items', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'aisle_1_unused')
    # ### end Alembic commands ###
